server {
    listen 80;
    
    # Increase maximum upload size if your frontend passes files through
    client_max_body_size 50M;

    # Where the root files will be stored
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Important: Route any request to index.html so React Router gets it
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Better cache control for static assets (js, css, images)
    location ~* \.(?:css|js|jpg|svg)$ {
        expires 30d;
        add_header Cache-Control "public";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
